apiVersion: v1
kind: Secret
metadata: 
  name: webapp-secret
type: Opaque
data:
  JWT_SECRET: YzJWamNtVjA=
  DBPASSWORD: bW9uZ29kYitzcnY6Ly9heWZhbnRpczUzOkFuZDNmbGlwJTIzQG1lcm4ueXc3aWRweC5tb25nb2RiLm5ldC9nb2FsU2V0dGVyP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==