# SERVER BACKEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: ayfantis53/mern-goalsetter-server
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
            - name: NODE_ENV
              value: 'Development'
            - name: JWT_SECRET
              valueFrom: 
                secretKeyRef:
                  name: webapp-secret
                  key: JWT_SECRET
            - name: ATLAS_URI
              valueFrom: 
                secretKeyRef:
                  name: webapp-secret
                  key: DBPASSWORD

---

# SERVICE FOR POD COMMUNCATION
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000