############################################################################################
#
#   ____                             ____             
#  / ___|  ___ _ ____   _____ _ __  |  _ \  _____   __
#  \___ \ / _ \ '__\ \ / / _ \ '__| | | | |/ _ \ \ / /
#   ___) |  __/ |   \ V /  __/ |    | |_| |  __/\ V / 
#  |____/ \___|_|    \_/ \___|_|    |____/ \___| \_/                               
#
# SERVER DEV
#
# https://github.com/ayfantis53/mern-memories/blob/master/client/Dockerfile.dev

############################################################################################
# Node Building Layer
# This is a MINIMAL RUNTIME image to run Node project
# For building Goals app backend locally
############################################################################################

# Use the official Node.js runtime as the parent image.
# This provides the necessary environment to run a Node.js application.
FROM node:latest

# Set the working directory inside the container.
# All subsequent instructions will be executed relative to this directory.
WORKDIR '/app'

# Copy the application's package.json and package-lock.json files to the container.
# This allows the installation of dependencies to leverage Docker's build cache effectively.
COPY ./package*.json ./

# Install project dependencies.
# Docker will only re-run this step if the package*.json files have changed, saving build time.
RUN npm install

# Copy the rest of the application's source code to the container's working directory.
COPY . .

# Specify the command to run when the container starts.
# This command builds the application, which is the default behavior when the container runs.
CMD ["npm", "run", "build"]
